export const environment = {
  production: true,
  urlApiAtendimento: 'https://api.atendimento.gestordepatios.app.br',
  urlApiDP: 'https://api.autoatendimento.webzi.com.br',
  urlApiSumup: 'https://api.sumup.com',
  urlApiWebziPay:'https://api.webzi.com.br',
  merchantCode: 'MDEUZAGC',
  urlReturnPayment: 'https://172.16.10.90:5001',
  clientId: 'cc_classic_kWwcKzywkLEZcOM9yEOpSrExMnnQl',
  clientSecret: 'cc_sk_classic_WHizzlncLknRFfNnRHFEukUuwX9j6xD2BMqqcyS3R6RNNuU7p8',
  afilliateKey: 'sup_afk_Ra3JUSxHPT7JQ2xcQpZaB4dp9BTElg93',
  redirectUri: 'sumupmobile://callback',
  apiKey: 'sup_pk_MOJxNHpvau9JivVO73JnrA5siGwmlmxNk',
  versao: '1.2.2',
};
